language: python
python:
  - "3.4"
before_install:
  - sudo apt-get update
install:
  - pip install -r requirements.txt
  - pip install pep8
  - sudo apt-get install texlive-latex-extra latexmk
script:
  - pep8 --ignore=E402,E501 generate.py
  - python generate.py --help
